\hypertarget{classmedpy_1_1core_1_1exceptions_1_1ArgumentError}{
\section{medpy.core.exceptions.ArgumentError Class Reference}
\label{classmedpy_1_1core_1_1exceptions_1_1ArgumentError}\index{medpy::core::exceptions::ArgumentError@{medpy::core::exceptions::ArgumentError}}
}


Thrown by an application when an invalid command line argument has been supplied.  




Inheritance diagram for medpy.core.exceptions.ArgumentError:\nopagebreak
\begin{figure}[H]
\begin{center}
\leavevmode
\includegraphics[width=264pt]{classmedpy_1_1core_1_1exceptions_1_1ArgumentError__inherit__graph}
\end{center}
\end{figure}


Collaboration diagram for medpy.core.exceptions.ArgumentError:\nopagebreak
\begin{figure}[H]
\begin{center}
\leavevmode
\includegraphics[width=264pt]{classmedpy_1_1core_1_1exceptions_1_1ArgumentError__coll__graph}
\end{center}
\end{figure}


\subsection{Detailed Description}
Thrown by an application when an invalid command line argument has been supplied. 

Definition at line 28 of file exceptions.py.



The documentation for this class was generated from the following file:\begin{DoxyCompactItemize}
\item 
/home/omaier/Programming/Python/medpy/src/medpy/core/exceptions.py\end{DoxyCompactItemize}
