\hypertarget{classmedpy_1_1core_1_1exceptions_1_1SubprocessError}{
\section{medpy.core.exceptions.SubprocessError Class Reference}
\label{classmedpy_1_1core_1_1exceptions_1_1SubprocessError}\index{medpy::core::exceptions::SubprocessError@{medpy::core::exceptions::SubprocessError}}
}


Thrown by an application when a subprocess execution failed.  




Inheritance diagram for medpy.core.exceptions.SubprocessError:\nopagebreak
\begin{figure}[H]
\begin{center}
\leavevmode
\includegraphics[width=274pt]{classmedpy_1_1core_1_1exceptions_1_1SubprocessError__inherit__graph}
\end{center}
\end{figure}


Collaboration diagram for medpy.core.exceptions.SubprocessError:\nopagebreak
\begin{figure}[H]
\begin{center}
\leavevmode
\includegraphics[width=274pt]{classmedpy_1_1core_1_1exceptions_1_1SubprocessError__coll__graph}
\end{center}
\end{figure}


\subsection{Detailed Description}
Thrown by an application when a subprocess execution failed. 

Definition at line 44 of file exceptions.py.



The documentation for this class was generated from the following file:\begin{DoxyCompactItemize}
\item 
/home/omaier/Programming/Python/medpy/src/medpy/core/exceptions.py\end{DoxyCompactItemize}
